
all:
  children:
    bastion_h:
      hosts:
        bastion:
          ansible_host: 51.250.1.109
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/fops-sysadm-diplom/ansible/file/keyssh
    web_hosts:
      hosts:
        webvm1:
          ansible_host: 10.129.1.10
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/fops-sysadm-diplom/ansible/file/keyssh
          ansible_ssh_common_args: >-
            -o ProxyCommand="ssh -i /root/fops-sysadm-diplom/ansible/file/keyssh -W %h:%p v3ll@51.250.1.109" -o StrictHostKeyChecking=no
        webvm2:
          ansible_host: 10.130.1.20
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/fops-sysadm-diplom/ansible/file/keyssh
          ansible_ssh_common_args: >-
            -o ProxyCommand="ssh -i /root/fops-sysadm-diplom/ansible/file/keyssh -W %h:%p v3ll@51.250.1.109" -o StrictHostKeyChecking=no
    prometheus:
      hosts:
        vm-prometheus:
          ansible_host: 10.129.1.11
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/fops-sysadm-diplom/ansible/file/keyssh
          ansible_ssh_common_args: >-
            -o ProxyCommand="ssh -i /root/fops-sysadm-diplom/ansible/file/keyssh -W %h:%p v3ll@51.250.1.109" -o StrictHostKeyChecking=no
    grafana:
      hosts:
        vm-grafana:
          ansible_host: 10.128.1.101
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/fops-sysadm-diplom/ansible/file/keyssh
          ansible_ssh_common_args: >-
            -o ProxyCommand="ssh -i /root/fops-sysadm-diplom/ansible/file/keyssh -W %h:%p v3ll@51.250.1.109" -o StrictHostKeyChecking=no
    elasticsearch:
      hosts:
        vm-ES:
          ansible_host: 10.130.1.21
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/fops-sysadm-diplom/ansible/file/keyssh
          ansible_ssh_common_args: >-
            -o ProxyCommand="ssh -i /root/fops-sysadm-diplom/ansible/file/keyssh -W %h:%p v3ll@51.250.1.109" -o StrictHostKeyChecking=no
    kibana:
      hosts:
        vm-kibana:
          ansible_host: 10.128.1.102
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/fops-sysadm-diplom/ansible/file/keyssh
          ansible_ssh_common_args: >-
            -o ProxyCommand="ssh -i /root/fops-sysadm-diplom/ansible/file/keyssh -W %h:%p v3ll@51.250.1.109" -o StrictHostKeyChecking=no
