---
- name: Ensure /etc/apt/apt.conf.d directory exists
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d
    state: directory
    mode: '0755'

- name: Ensure APT proxy configuration file exists
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/01proxy
    state: touch 

# Настраиваем прокси для APT
- name: Set APT proxy
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/01proxy
    line: 'Acquire::http::Proxy "http://10.128.1.100:3128/";'
    state: present

- name: Установить необходимые пакеты для Docker
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose 
    state: present
    update_cache: yes

- name: Убедиться, что сервис Docker запущен
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Запустить контейнер Grafana
  community.docker.docker_container:
    name: grafana
    image: huecker.io/grafana/grafana
    state: started
    restart_policy: always
    published_ports:
      - "3000:3000"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "loh"  
    volumes:
      - grafana-storage:/var/lib/grafana 
      
- name: Создать Docker volume для Grafana
  community.docker.docker_volume:
    name: grafana-storage
    state: present

