---
- name: Ensure /etc/apt/apt.conf.d directory exists
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d
    state: directory
    mode: '0755'

- name: Ensure APT proxy configuration file exists
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/01proxy
    state: touch 

# Настраиваем прокси для APT
- name: Set APT proxy
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/01proxy
    line: 'Acquire::http::Proxy "http://10.128.1.100:3128/";'
    state: present

# # Проверяем наличие доступа через прокси
# - name: Test connection to the internet via proxy
#   ansible.builtin.command: curl -I http://archive.ubuntu.com/ubuntu
#   register: curl_result
#   failed_when: "'200 OK' not in curl_result.stdout"
#   ignore_errors: true

# - name: Show result of proxy connection test
#   ansible.builtin.debug:
#     var: curl_result.stdout

# Устанавливаем Nginx
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

# Копируем конфигурацию Nginx из шаблона
- name: Copy Nginx configuration file
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restart Nginx

# Запускаем Nginx и добавляем в автозагрузку
- name: Ensure Nginx is running and enabled on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Проверить статус Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
  register: nginx_status
  ignore_errors: true

- name: Показать статус Nginx
  ansible.builtin.debug:
    var: nginx_status.stdout_lines