# ============================== Filebeat inputs ===============================
filebeat.inputs:

- type: filestream
  id: nginx-logs
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log

# ============================== Output ===============================
output.elasticsearch:
  hosts: ["https://10.130.1.21:9200"] 
  username: "elastic"
  password: "loh"
  ssl.verification_mode: "none"

  indices:
    - index: "nginx-logs-%{+yyyy.MM.dd}" 

# ============================== Logging ===============================
# logging.level: info
# logging.to_files: true
# logging.files:
#   path: /var/log/filebeat
#   name: filebeat.log
#   keepfiles: 7
#   permissions: 0644
